import { dracula } from "react-code-blocks";
import { CodeBlockTheme } from "react-code-blocks/dist/types";

export enum Theme {
  "a11yDark",
  "a11yLight",
  "anOldHope",
  "androidstudio",
  "arta",
  "atomOneDark",
  "atomOneLight",
  "codepen",
  "dracula",
  "far",
  "github",
  "googlecode",
  "hopscotch",
  "hybrid",
  "irBlack",
  "monoBlue",
  "monokaiSublime",
  "monokai",
  "nord",
  "noctisViola",
  "obsidian",
  "ocean",
  "paraisoDark",
  "paraisoLight",
  "pojoaque",
  "purebasic",
  "railscast",
  "rainbow",
  "shadesOfPurple",
  "solarizedDark",
  "solarizedLight",
  "sunburst",
  "tomorrowNightBlue",
  "tomorrowNightBright",
  "tomorrowNightEighties",
  "tomorrowNight",
  "tomorrow",
  "vs2015",
  "xt256",
  "zenburn",
}

export const codeBlockThemeMap = new Map<Theme, CodeBlockTheme>([[Theme.dracula, dracula]]);
