/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Dev_toolsRouteImport } from './routes/dev_tools'
import { Route as Ast_power_searchRouteImport } from './routes/ast_power_search'

const Dev_toolsRoute = Dev_toolsRouteImport.update({
  id: '/dev_tools',
  path: '/dev_tools',
  getParentRoute: () => rootRouteImport,
} as any)
const Ast_power_searchRoute = Ast_power_searchRouteImport.update({
  id: '/ast_power_search',
  path: '/ast_power_search',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/ast_power_search': typeof Ast_power_searchRoute
  '/dev_tools': typeof Dev_toolsRoute
}
export interface FileRoutesByTo {
  '/ast_power_search': typeof Ast_power_searchRoute
  '/dev_tools': typeof Dev_toolsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/ast_power_search': typeof Ast_power_searchRoute
  '/dev_tools': typeof Dev_toolsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/ast_power_search' | '/dev_tools'
  fileRoutesByTo: FileRoutesByTo
  to: '/ast_power_search' | '/dev_tools'
  id: '__root__' | '/ast_power_search' | '/dev_tools'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Ast_power_searchRoute: typeof Ast_power_searchRoute
  Dev_toolsRoute: typeof Dev_toolsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dev_tools': {
      id: '/dev_tools'
      path: '/dev_tools'
      fullPath: '/dev_tools'
      preLoaderRoute: typeof Dev_toolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ast_power_search': {
      id: '/ast_power_search'
      path: '/ast_power_search'
      fullPath: '/ast_power_search'
      preLoaderRoute: typeof Ast_power_searchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  Ast_power_searchRoute: Ast_power_searchRoute,
  Dev_toolsRoute: Dev_toolsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
